# ==============================================================================
# External Secrets Operator: DEV TIBCO BWCE Secrets
# ==============================================================================
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bwce-app-secrets
  namespace: nubenetes-dev-bwce
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: bwce-app-credentials
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: secret/dev/bwce/database
        property: password
    - secretKey: JMS_PASSWORD
      remoteRef:
        key: secret/dev/bwce/jms
        property: password
    - secretKey: DATADOG_API_KEY
      remoteRef:
        key: secret/dev/datadog
        property: api-key
