apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: datadog-api-credentials
  namespace: nubenetes-prod-bwce
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: datadog-api-credentials
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: secret/prod/datadog
        property: api-key
    - secretKey: app-key
      remoteRef:
        key: secret/prod/datadog
        property: app-key
